---
- name: reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart tailscaled
  become: true
  ansible.builtin.systemd:
    name: tailscaled
    state: restarted
